#vscode REST cli
#GET http://localhost:3001/api/mywines
GET http://localhost:3001/api/users
###
DELETE  http://localhost:3001/api/mywines/1
###

POST http://localhost:3001/api/users
Content-type: application/json

{
  "name": "Test",
  "username": "testuser",
  "password":"testpass"
  
}
###
POST http://localhost:3001/api/mywines
Content-type: application/json
Authorization: Bearer hereshouldbetoken

{
  "name": "Item 4",
  "description": "My new item",
  "userId":3
  
}
###
POST http://localhost:3001/api/login
Content-type: application/json

{
  "username": "mina",
  "password": "salainen",
  
}